; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Universal SQL Client"
#define MyAppVersion "1.35"
#define MyAppPublisher "Datafluent BD"
#define MyAppURL "https://www.datafluent.team"
#define MyAppExeName "Universal SQL Client.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6A6E3F74-646B-414F-866F-1DB1E5AD7194}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=license.txt
; Allow user to choose between 'All Users' (admin) and 'Current User' (lowest).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
UsePreviousPrivileges=no
OutputDir=dist
OutputBaseFilename=Universal_SQL_Client_WINDOWS_1.35_setup
SetupIconFile=assets\app_icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "dist\Universal SQL Client\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\Universal SQL Client\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "databases\*"; DestDir: "{app}\databases"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\app_icon.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\assets\app_icon.ico"
Name: "{autoprograms}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

[UninstallDelete]
; Remove everything left in the install folder after the uninstaller runs
Type: filesandordirs; Name: "{app}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  { The Inno Setup uninstall key that stores the install scope (All Users vs Current User). }
  { Deleting it ensures the All Users/Current User dialog is shown on the next fresh install. }
  UninstallKeyHKLM = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{6A6E3F74-646B-414F-866F-1DB1E5AD7194}_is1';
  UninstallKeyHKCU = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{6A6E3F74-646B-414F-866F-1DB1E5AD7194}_is1';

procedure InitializeWizard;
begin
  { Pre-select "I accept the agreement" on the license page }
  WizardForm.LicenseAcceptedRadio.Checked := True;
end;

procedure DeinitializeUninstall;
begin
  RegDeleteKeyIncludingSubkeys(HKLM, UninstallKeyHKLM);
  RegDeleteKeyIncludingSubkeys(HKCU, UninstallKeyHKCU);
end;
