; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Universal SQL Client"
#define MyAppVersion "1.44"
#define MyAppPublisher "Datafluent BD"
#define MyAppURL "https://www.datafluent.team"
#define MyAppExeName "Universal SQL Client.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6A6E3F74-646B-414F-866F-1DB1E5AD7194}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; Lets setup/uninstall detect a running instance (mutex is held by main.py)
; and show the standard close-application prompt instead of file-in-use errors.
AppMutex=UniversalSQLClientAppMutex
CloseApplications=yes
CloseApplicationsFilter=*.exe
RestartApplications=no
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
DefaultGroupName={#MyAppName}
LicenseFile=license.txt
; Allow user to choose between 'All Users' (admin) and 'Current User' (lowest).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
UsePreviousPrivileges=no
OutputDir=dist
OutputBaseFilename=Universal_SQL_Client_WINDOWS_{#MyAppVersion}_setup
SetupIconFile=assets\app_icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
ConfirmUninstall=Are you sure you want to uninstall %1?%n%n(You will be asked whether to keep your saved connections and settings on the next screen.)

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; PyInstaller output — includes all Python runtime, app code, assets, ui, pg_client, etc.
Source: "dist\Universal SQL Client\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Databases folder (may contain writable user data; kept separate from PyInstaller output)
Source: "databases\*"; DestDir: "{app}\databases"; Flags: ignoreversion recursesubdirs createallsubdirs
; Assets folder (icons, images; kept separate so icon paths resolve correctly at install time)
Source: "assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs
; Oracle Instant Client — shipped via installer to keep PyInstaller bundle lean
Source: "resources\oracle\instantclient\*"; DestDir: "{app}\resources\oracle\instantclient"; Flags: ignoreversion recursesubdirs createallsubdirs
; CData connector wheels (ServiceNow, CSV) — large binaries kept outside PyInstaller bundle
Source: "drivers\*"; DestDir: "{app}\drivers"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\app_icon.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\assets\app_icon.ico"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

[UninstallDelete]
; Remove everything left in the install folder after the uninstaller runs
Type: filesandordirs; Name: "{app}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  { The Inno Setup uninstall key that stores the install scope (All Users vs Current User). }
  { Deleting it ensures the All Users/Current User dialog is shown on the next fresh install. }
  UninstallKeyHKLM = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{6A6E3F74-646B-414F-866F-1DB1E5AD7194}_is1';
  UninstallKeyHKCU = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{6A6E3F74-646B-414F-866F-1DB1E5AD7194}_is1';

{ InitializeWizard is intentionally omitted.
  Inno Setup's default LicensePage behaviour already leaves
  'I do not accept' unselected when a LicenseFile is specified — no override needed. }

var
  RemoveConnections: Boolean;
  RemoveSettings: Boolean;
  RemoveCreds: Boolean;
  ChkBase, Chk1, Chk2, Chk3, ChkMaster: TNewCheckBox;

function ParamEnabled(const Name: String): Boolean;
begin
  Result := ExpandConstant('{param:' + Name + '|0}') = '1';
end;

function InitializeUninstall(): Boolean;
begin
  { Interactive mode defaults to keep everything; the options page below
    lets the user opt in. Silent mode keeps everything unless the caller
    passes /REMOVECONNECTIONS=1 /REMOVESETTINGS=1 /REMOVECREDS=1. }
  RemoveConnections := UninstallSilent and ParamEnabled('REMOVECONNECTIONS');
  RemoveSettings := UninstallSilent and ParamEnabled('REMOVESETTINGS');
  RemoveCreds := UninstallSilent and ParamEnabled('REMOVECREDS');
  Result := True;
end;

procedure ChkMasterClick(Sender: TObject);
begin
  if ChkMaster.Checked then
  begin
    Chk1.Checked := True;
    Chk2.Checked := True;
    Chk3.Checked := True;
    Chk1.Enabled := False;
    Chk2.Enabled := False;
    Chk3.Enabled := False;
  end
  else
  begin
    Chk1.Enabled := True;
    Chk2.Enabled := True;
    Chk3.Enabled := True;
  end;
end;

procedure InitializeUninstallProgressForm();
var
  Page: TNewNotebookPage;
  GoButton: TNewButton;
  Header, DescBase, DescMaster, Desc1, Desc2, Desc3, Footer: TNewStaticText;
  BaseTop, BaseLeft, BaseWidth: Integer;
  OrigName, OrigDesc: String;
  OrigCancelEnabled: Boolean;
  OrigCancelModal: Integer;
begin
  if UninstallSilent then
    Exit;

  BaseTop := UninstallProgressForm.StatusLabel.Top;
  BaseLeft := UninstallProgressForm.StatusLabel.Left;
  BaseWidth := UninstallProgressForm.StatusLabel.Width;

  { Extra "Uninstall" button that closes our options page with mrOK. }
  GoButton := TNewButton.Create(UninstallProgressForm);
  GoButton.Parent := UninstallProgressForm;
  GoButton.Left := UninstallProgressForm.CancelButton.Left
    - UninstallProgressForm.CancelButton.Width - ScaleX(10);
  GoButton.Top := UninstallProgressForm.CancelButton.Top;
  GoButton.Width := UninstallProgressForm.CancelButton.Width;
  GoButton.Height := UninstallProgressForm.CancelButton.Height;
  GoButton.Caption := 'Uninstall';
  GoButton.ModalResult := mrOk;
  GoButton.TabOrder := UninstallProgressForm.CancelButton.TabOrder;
  UninstallProgressForm.CancelButton.TabOrder := GoButton.TabOrder + 1;

  Page := TNewNotebookPage.Create(UninstallProgressForm);
  Page.Notebook := UninstallProgressForm.InnerNotebook;
  Page.Parent := UninstallProgressForm.InnerNotebook;
  Page.Align := alClient;
  UninstallProgressForm.InnerNotebook.ActivePage := Page;

  Header := TNewStaticText.Create(UninstallProgressForm);
  Header.Parent := Page;
  Header.Top := BaseTop;
  Header.Left := BaseLeft;
  Header.Width := BaseWidth;
  Header.Height := ScaleY(16);
  Header.AutoSize := False;
  Header.ShowAccelChar := False;
  Header.Caption := 'Select the components you want to remove:';

  ChkBase := TNewCheckBox.Create(UninstallProgressForm);
  ChkBase.Parent := Page;
  ChkBase.Top := BaseTop + ScaleY(24);
  ChkBase.Left := BaseLeft;
  ChkBase.Width := BaseWidth;
  ChkBase.Caption := 'Remove Universal SQL Client application files';
  ChkBase.Checked := True;
  ChkBase.Enabled := False;

  DescBase := TNewStaticText.Create(UninstallProgressForm);
  DescBase.Parent := Page;
  DescBase.Top := ChkBase.Top + ScaleY(18);
  DescBase.Left := BaseLeft + ScaleX(16);
  DescBase.Width := BaseWidth - ScaleX(16);
  DescBase.Height := ScaleY(16);
  DescBase.AutoSize := False;
  DescBase.ShowAccelChar := False;
  DescBase.Caption := 'Required. Uninstalls the program from your computer.';

  ChkMaster := TNewCheckBox.Create(UninstallProgressForm);
  ChkMaster.Parent := Page;
  ChkMaster.Top := DescBase.Top + ScaleY(24);
  ChkMaster.Left := BaseLeft;
  ChkMaster.Width := BaseWidth;
  ChkMaster.Caption := 'Completely remove all user data and settings';
  ChkMaster.Checked := False;
  ChkMaster.OnClick := @ChkMasterClick;

  DescMaster := TNewStaticText.Create(UninstallProgressForm);
  DescMaster.Parent := Page;
  DescMaster.Top := ChkMaster.Top + ScaleY(18);
  DescMaster.Left := BaseLeft + ScaleX(16);
  DescMaster.Width := BaseWidth - ScaleX(16);
  DescMaster.Height := ScaleY(16);
  DescMaster.AutoSize := False;
  DescMaster.ShowAccelChar := False;
  DescMaster.Caption := 'Select this to permanently delete everything.';

  Chk1 := TNewCheckBox.Create(UninstallProgressForm);
  Chk1.Parent := Page;
  Chk1.Top := DescMaster.Top + ScaleY(24);
  Chk1.Left := BaseLeft + ScaleX(16);
  Chk1.Width := BaseWidth - ScaleX(16);
  Chk1.Caption := 'Delete saved connections and query history';
  Chk1.Checked := False;

  Desc1 := TNewStaticText.Create(UninstallProgressForm);
  Desc1.Parent := Page;
  Desc1.Top := Chk1.Top + ScaleY(18);
  Desc1.Left := BaseLeft + ScaleX(32);
  Desc1.Width := BaseWidth - ScaleX(32);
  Desc1.Height := ScaleY(26);
  Desc1.AutoSize := False;
  Desc1.ShowAccelChar := False;
  Desc1.Caption := 'Removes servers and hierarchy.db in ' +
    '%APPDATA%\Universal SQL Client.';

  Chk2 := TNewCheckBox.Create(UninstallProgressForm);
  Chk2.Parent := Page;
  Chk2.Top := Desc1.Top + ScaleY(26);
  Chk2.Left := BaseLeft + ScaleX(16);
  Chk2.Width := BaseWidth - ScaleX(16);
  Chk2.Caption := 'Delete settings and terminal history';
  Chk2.Checked := False;

  Desc2 := TNewStaticText.Create(UninstallProgressForm);
  Desc2.Parent := Page;
  Desc2.Top := Chk2.Top + ScaleY(18);
  Desc2.Left := BaseLeft + ScaleX(32);
  Desc2.Width := BaseWidth - ScaleX(32);
  Desc2.Height := ScaleY(26);
  Desc2.AutoSize := False;
  Desc2.ShowAccelChar := False;
  Desc2.Caption := 'Removes preferences, psql_history.json, and registry settings.';

  Chk3 := TNewCheckBox.Create(UninstallProgressForm);
  Chk3.Parent := Page;
  Chk3.Top := Desc2.Top + ScaleY(26);
  Chk3.Left := BaseLeft + ScaleX(16);
  Chk3.Width := BaseWidth - ScaleX(16);
  Chk3.Caption := 'Sign out and delete stored credentials';
  Chk3.Checked := False;

  Desc3 := TNewStaticText.Create(UninstallProgressForm);
  Desc3.Parent := Page;
  Desc3.Top := Chk3.Top + ScaleY(18);
  Desc3.Left := BaseLeft + ScaleX(32);
  Desc3.Width := BaseWidth - ScaleX(32);
  Desc3.Height := ScaleY(26);
  Desc3.AutoSize := False;
  Desc3.ShowAccelChar := False;
  Desc3.Caption := 'Removes login tokens from Windows Credential Manager.';


  OrigName := UninstallProgressForm.PageNameLabel.Caption;
  OrigDesc := UninstallProgressForm.PageDescriptionLabel.Caption;
  OrigCancelEnabled := UninstallProgressForm.CancelButton.Enabled;
  OrigCancelModal := UninstallProgressForm.CancelButton.ModalResult;

  UninstallProgressForm.PageNameLabel.Caption := 'Uninstall {#MyAppName}';
  UninstallProgressForm.PageDescriptionLabel.Caption :=
    'Remove user data and settings';
  UninstallProgressForm.CancelButton.Enabled := True;
  UninstallProgressForm.CancelButton.ModalResult := mrCancel;

  if UninstallProgressForm.ShowModal = mrCancel then
    Abort;

  RemoveConnections := Chk1.Checked;
  RemoveSettings := Chk2.Checked;
  RemoveCreds := Chk3.Checked;

  GoButton.Visible := False;
  UninstallProgressForm.PageNameLabel.Caption := OrigName;
  UninstallProgressForm.PageDescriptionLabel.Caption := OrigDesc;
  UninstallProgressForm.CancelButton.Enabled := OrigCancelEnabled;
  UninstallProgressForm.CancelButton.ModalResult := OrigCancelModal;
  UninstallProgressForm.InnerNotebook.ActivePage :=
    UninstallProgressForm.InstallingPage;
end;

procedure DeleteCredential(Target: String);
var
  ResultCode: Integer;
begin
  Exec('cmdkey.exe', '/delete:"' + Target + '"', '', SW_HIDE,
    ewWaitUntilTerminated, ResultCode);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    if RemoveConnections then
    begin
      Log('Uninstall: deleting %APPDATA%\Universal SQL Client');
      DelTree(ExpandConstant('{userappdata}\Universal SQL Client'), True, True, True);
    end;
    if RemoveSettings then
    begin
      Log('Uninstall: deleting %APPDATA%\DBExplorer and HKCU\Software\DBExplorer');
      DelTree(ExpandConstant('{userappdata}\DBExplorer'), True, True, True);
      RegDeleteKeyIncludingSubkeys(HKCU, 'Software\DBExplorer');
    end;
    if RemoveCreds then
    begin
      Log('Uninstall: deleting stored credentials');
      // Best effort: keyring WinVaultKeyring stores under the service name or
      // {username}@{service} compound targets. Missing entries are ignored.
      DeleteCredential('Universal SQL Client');
      DeleteCredential('access_token@Universal SQL Client');
      DeleteCredential('refresh_token@Universal SQL Client');
      DeleteCredential('user@Universal SQL Client');
      DeleteCredential('avatar@Universal SQL Client');
    end;
  end;
end;

procedure DeinitializeUninstall;
begin
  RegDeleteKeyIncludingSubkeys(HKLM, UninstallKeyHKLM);
  RegDeleteKeyIncludingSubkeys(HKCU, UninstallKeyHKCU);
end;
